#http://docs.travis-ci.com/user/languages/android/
language: android

sudo: false
jdk: oraclejdk8
android:
  components:
      - tools
      - platform-tools
      - build-tools-25.0.2
      - android-27
      - extra-android-support
      - extra-android-m2repository
  licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+
addons:
  sonarqube:
    organization: "shoeper-github"
    branches:
     - cleanup
     - master
before_install:
    - yes | sdkmanager "platforms;android-27"
script:
    - cp app/key.properties.example app/key.properties
    - cp app/key.properties.example app/debugkey.properties
    - keytool -genkey -v -keystore app/debug.keystore -alias AndroidDebugKey -keyalg RSA -keysize 2048 -validity 1 -storepass android -keypass android -dname "cn=TEST, ou=TEST, o=TEST, c=TE"
    - ./gradlew clean assemble
    - sonar-scanner
# reference https://docs.travis-ci.com/user/sonarqube/
# reference https://docs.travis-ci.com/user/languages/android
